title: "次世代校務DX基盤の教科書 1：調達前に知っておきたい10の原則"
summary: "文科省と総務省の異なるセキュリティ方針という現実的な課題に直面する教育現場向けに、児童生徒の個人情報保護を最優先とした次世代校務DX導入の「考え方」を体系的に解説。製品導入ありきではなく、本来の目的である個人情報保護を軸に、限られた予算と人的リソースの中で現実的にどう対応すべきかを詳しく説明します。年間200件発生するセキュリティインシデント事例から学ぶ実践的なアプローチを提供。"
topics: ["校務DX", "個人情報保護", "セキュリティインシデント", "ゼロトラスト", "教育セキュリティ"]
published: false
price: 500 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter01  # はじめに - 本書の目的と調達前に知っておきたい10の原則
  - chapter02  # 製品導入が目的になっていませんか？本来の目的は児童生徒の個人情報保護です
  - chapter03  # なぜ今「次世代校務DX」なのか？従来システムの限界と新たな方向性
  - chapter04  # 文部科学省が「端末1台化」を推進する理由
  - chapter05  # 文科省と総務省の異なるセキュリティアプローチ
  - chapter06  # NIST準拠への移行戦略とコスト分析
  - chapter07  # 現実的な解決策の模索と段階的移行戦略
  - chapter08  # 実践的個人情報保護運用設計 - 年間200件のインシデント事例から学ぶ
  - chapter09  # 実効性のあるセキュリティ対策の実装 - 技術と運用の最適バランス
  - chapter10  # 教職員の個人情報保護意識向上と体制構築
  - chapter11  # リスクベースでの投資優先順位決定
  - chapter12  # 個人情報漏洩事例から学ぶ教訓
  - chapter13  # 個人情報保護を中心とした導入計画
  - chapter14  # おわりに
  - chapter15  # 用語集
  - chapter16  # 参考文献
  - chapter17  # 
  - chapter18  # ライセンス・免責事項
