title: "持続可能なAI活用のススメ 〜認知負債という見えない敵と戦うガードレール戦略〜"
summary: "生成AI時代において、便利さと引き換えに蓄積される「認知負債」という問題に着目し、長期的に持続可能なAI活用を実現するためのガードレール設計手法を体系的に解説する。個人・チーム・組織レベルでの実践的な対策と、人間の思考力を枯渇させない仕組み作りを提案。"
topics: ["AI", "生成AI", "認知負債", "ガードレール", "持続可能性"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - prologue
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - epilogue
  - reference
  - license
