title: "生成AI短期集中使用による認知機能低下の現象学的分析と神経科学的考察"
summary: "生成AI短期集中使用による認知機能低下の現象学的分析と神経科学的考察。筆者の実体験に基づく1.5ヶ月間の認知的負債蓄積プロセスの詳細な分析と、8週間の認知機能回復プログラムを提案する学術論文。"
topics: ["AI", "認知科学", "神経科学", "認知負債", "デジタル健康"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter1
