title: "「先生、それAIに丸投げですか？」教員の認知負債を激増させる生成AI失敗事例30選と賢い活用術"
summary: "MIT発の「認知負債」概念を教育現場に適用し、生成AIの誤った使い方が教員の専門性や思考力を低下させる30の具体例を提示。各事例について問題点を分析し、認知負債を防ぎながら効果的にAIを活用する実践的な方法を解説する実践書です。"
topics: ["生成AI", "教育", "認知負債", "教員", "AI活用"]
published: true
price: 0 # 有料の場合200〜5000
license: "CC BY-NC 4.0" # クリエイティブ・コモンズ 表示-非営利 4.0
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter01  # 認知負債という見えない借金
  - chapter02  # 授業設計・計画で陥る5つの失敗
  - chapter03  # 評価・指導で起こる5つの過ち
  - chapter04  # 生徒対応・コミュニケーションの5つの落とし穴
  - chapter05  # 校務・事務処理での5つの誤用
  - chapter06  # 進路指導・特別活動での8つの失敗
  - chapter07  # 専門性と成長の4つの危機
  - chapter08  # 認知負債を防ぐ賢い活用術
  - chapter09  # 未来の教育とAIの共存
  - appendix   # 付録：認知負債チェックリスト
  - references # 参考文献一覧
  - license    # ライセンス情報

