title: "Microsoft Learning AcceleratorとForms API完全ガイド"
summary: "Microsoft Learning Acceleratorの教育支援ツール群とMicrosoft Forms APIの統合方法を、実装から運用まで包括的に解説。教育機関のIT管理者、教育テクノロジー担当者、開発者向けの実践的なガイドブック。"
topics: ["microsoft", "education", "api", "teams", "forms"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - chapter6
  - chapter7
  - chapter8
  - chapter9
  - chapter10
toc_depth: 3  # 目次の表示段階を指定。1〜3の範囲で設定可能。省略した場合は2
