title: "次世代校務DX基盤の教科書 2：個人情報保護と業務最適化を実現する調達戦略"
summary: |
  教育委員会担当者が次世代校務DX基盤を正しく調達するためのRFI（情報提供依頼書）作成に特化した実践的手法を詳解。第1巻で確立した「児童生徒の個人情報保護最優先」の原則を維持しながら、教職員の働き方改革も同時に実現する調達戦略の基礎から、RFI設計・分析、RFP作成まで体系的に解説。NIST SP 800-207準拠のゼロトラストセキュリティ要件を教育現場で実現可能な形で記述する方法、ベンダー回答の客観的分析手法、実現可能なRFP作成テクニックを、ITやセキュリティの専門知識がない担当者でも実践できるよう具体的テンプレートとともに提供。
topics: ["校務DX", "ゼロトラスト", "調達戦略", "RFI", "RFP"]
published: false
price: 800 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter01  # 個人情報保護と業務最適化を実現する調達戦略の基礎
  - chapter02  # 次世代校務DX基盤のRFI設計：個人情報保護と業務効率化を両立するクラウド基盤調達
  - chapter03  # RFI回答の体系的分析：次世代校務DX基盤選定のための情報整理と評価手法
  - chapter04  # RFP作成の実践的手法：ステップバイステップで学ぶ提案依頼書設計
  - chapter05  # まとめ：次世代校務DX基盤の成功する調達に向けて
  - appendix   # NIST Zero Trust Security準拠の次世代校務DX基盤 RFI・RFP実践テンプレート
